### ISSUE TITLE
Is not working for bungeecord command

### ISSUE THREAD

**Issue by WaffleMast3r** [XHawk87/CreateYourOwnMenus#10]
I type this command:
/menu script add /pendeploy create vanila @p
after I create the menu.
Than I edit the menu and I put the item in and save it.
And when I try to click on item I receive that error:
http://prntscr.com/f2c1z9

**Comment by WaffleMast3r** [comment]
never mind is not working with bungeecord commands only for /server command

**Comment by BatDev0** [comment]
It might be an error with your syntax. You should look at the bungee cord docs, and check if you are doing the right command.
