### ISSUE TITLE
Menu to Menu

### ISSUE THREAD

**Issue by Chenchoon** [XHawk87/CreateYourOwnMenus#12]
How do I make my menu open into another menu, when I try to add a command it says "%player% not found"

**Comment by XHawk87** [comment]
Say you have two menus: myMenu and myOtherMenu

In myMenu, you place an item with the command:

`/menu open @p myOtherMenu`

When clicked, the player will be taken to myOtherMenu.

**Comment by Chenchoon** [comment]
ah I see now thanks, another question how do i use /requirepermission [node]

**Comment by Chenchoon** [comment]
Oh ignore that I found my answer thanks
