### ISSUE TITLE
Permission Nodes

### ISSUE THREAD

**Issue by TacoShredder** [XHawk87/CreateYourOwnMenus#16]
Is it possible to give a permission node to open a specific menu, rather than all menus.

**Comment by XHawk87** [comment]
cyom.menu.[id of the menu] (without the square brackets)

See [Specific Menu Use at the bottom of Commands and Permissions](https://dev.bukkit.org/projects/createyourownmenus/pages/commands-and-permissions#Specific_Menu_Use) for more details
