### ISSUE TITLE
Require items

### ISSUE THREAD

**Issue by GoldenMushroom** [XHawk87/CreateYourOwnMenus#18]
How to make it so requires you to have an item for the next commands to run? I've tried the first commmand to be /testfor @p[r=10] {Inventory:[{id:"minecraft:diamond_sword"}]} but sience there is { } it just asks you to imput whatever you want there. Also the next command seems to run regardless wether the /testfor was succesfull or no

**Comment by XHawk87** [comment]
Hi @GoldenMushroom 

You have a couple of ways to do this: In 1.12+ you can use functions to run all of the commands, and in the CYOM menu item, you just put /function your_namespace:your_function_name. You can find more about functions on the Minecraft wiki.

If you're using pre-1.12, you may need a command scripting plugin such as Skript. With that you can create a custom command that does all of the testing of items etc, and you run it using the CYOM menu item.
