### ISSUE TITLE
How can I open a menu with command?

### ISSUE THREAD

**Issue by lazaros282** [XHawk87/CreateYourOwnMenus#22]
I've been working with this plugin and I know about it. I know how to open menu by clicking item and editing the menus using this plugin but what should I do to open a menu using a command like /shop ?

**Comment by XHawk87** [comment]
There are various command aliasing plugins around that you can use to map `/shop -> /menu open @p my_shop_menu`

I would personally use Skript, as it lets you do much more than just command aliasing that vastly extends what you can do with CYOM. http://en.njol.ch/projects/skript/doc/commands
