### ISSUE TITLE
Can i make a status of map or world?

### ISSUE THREAD

**Issue by GIGAADAM** [XHawk87/CreateYourOwnMenus#24]
Just im making a menu for MC Server and i need to make a BedWars menu
Like if map is full the item is Wool 14 (Red Wool) if is map empty the item is Wool 5 (Lime Wool) and if is starting the item is Wool 4 (Yellow Wool)
Please help me
Thanks

-GIGAADAM
Adam Otahal

**Comment by XHawk87** [comment]
You can create 3 separate menus, one for each colour wool. Then you'll need some kind of script or triggers or function to run depending on the status of BedWars that runs the command to open that menu for the player. I don't really know how BedWars works, so you'd have to ask someone who knows more about that.

**Comment by GIGAADAM** [comment]
Ok thanks :)
