### ISSUE TITLE
1.13 Items don't work

### ISSUE THREAD

**Issue by DracoDragon93** [XHawk87/CreateYourOwnMenus#25]
I can't edit most new items that were created in 1.13 like Tridents, Turtle Eggs, Kelp, Fish Buckets, and anything that was new in 1.13. If I try to use /menu script append or /menu script title it will give the error "You must be holding a menu item", but the commands will work on anything that isn't from 1.13.

**Comment by XHawk87** [comment]
I have investigated this issue and found the problem. We are still currently using magic numbers to check items, and it is likely that new items in 1.13 don't have a magic ID number, so would return 0 and become confused with empty air. So basically it thinks you have nothing in your hand. 

I'll try to get a fix for this up this weekend, but I may need help testing it as I no longer run any Bukkit-based servers.

**Comment by XHawk87** [comment]
I've made an update and it is ready for testing. Please don't put this on a live server until you've thoroughly tested it: https://github.com/XHawk87/CreateYourOwnMenus/releases/tag/0.5.11
