### ISSUE TITLE
Can you do multiple commands?

### ISSUE THREAD

**Issue by BatDev0** [XHawk87/CreateYourOwnMenus#28]
Hey, 

I am trying to make a shop. I want to see if i can take the item, money, and give the item. Or vise versa. I have been racking my brain. I couldnt think of anything. If you could help me out. That would be great.

**Comment by XHawk87** [comment]
Yes, you can add multiple commands to a menu script. It will run them in order from top to bottom as each one is completed successfully. If a command fails then the script will stop. This can be used to create a shop script using one of the various /require commands at the top. See the docs for details
