### ISSUE TITLE
Menu script isn't working?

### ISSUE THREAD

**Issue by jumpy72red** [XHawk87/CreateYourOwnMenus#29]
I have made a new server and making a few menus for it, including a Main Menu (id: MM) and Events (id: E) menu for it. I am making a block that you click on in the Main Menu open the Events menu. So I script a dispenser with this command: /menu script add menu script open @p E. It doesn't do anything. I make sure it is not just incorrect placement of the @p by moving it around to different places, but no change. So, after deleting all the menu script open @p E from the block, I add /menu script add whisper ZeroDamagePVP Test. This doesn't work either. I made sure it was not just a block by using a nether star as well. No commands work with /menu script add. Please could I have some help?

**Comment by XHawk87** [comment]
`menu script open` is not a command. I'm guessing you're looking for `/menu open`

Also, don't forget the slashes. If a menu script line doesn't start with a forward slash, it is treated as normal item lore.

**Comment by jumpy72red** [comment]
Ahhh thank you so much! And no, i didn't mean /menu script open
