### ISSUE TITLE
How do I stop CYOM from taking money from vault when you don't have enough money?

### ISSUE THREAD

**Issue by jumpy72red** [XHawk87/CreateYourOwnMenus#30]
Sorry, i'm not sure if this is the right place for this.
The title is pretty self-explanatory, is there a way to stop CYOM taking, say, £500 from vault if your money with vault is £100?

Edit: Changed "it" to CYOM

**Comment by XHawk87** [comment]
You can use /requirecurrency [amount] in a menu script before that to ensure they have enough Vault currency before doing the next command

**Comment by jumpy72red** [comment]
Thats great, thank you so much!
Thank you,
Harry Carr
