### ISSUE TITLE
Translating is possible?

### ISSUE THREAD

**Issue by Undermmon** [XHawk87/CreateYourOwnMenus#31]
I read on bukkit that is possible to translate the messages editing the  lang-eng.ylm, but there is none on the config folder, so i assume that i need to edit the one inside the .jar? Is that correct? I wanted to contribute with a translation, but i am not sure if the plugin supports that.

**Comment by XHawk87** [comment]
You can use the [LanguageAPI plugin](https://dev.bukkit.org/projects/languageapi) to do translations

**Comment by Undermmon** [comment]
Thanks, i'll look into that. Probably would be a great improvement to clarify that on the Bukkit page, i didn't found that information there even though i carefully searched the page for info.

**Comment by XHawk87** [comment]
Done
