### ISSUE TITLE
Add support for off-hand slot

### ISSUE THREAD

**Issue by TheRealGriind** [XHawk87/CreateYourOwnMenus#32]
Hello! I jsut noticed that if I try placing something in my offhand by putting it directly into the slot it say's "This is not a valid menu item" not when I try taking something out either, the only way im able to get it in/out of the offhand slot is by using the keyboard shortcut.

Im on 1.15.2.
Plugin version is 0.6.3

**Comment by Andrei12333** [comment]
Use the key "F" with the item you want in your off-hand slot or to remove it.
