### ISSUE TITLE
How do i give a player the menu item

### ISSUE THREAD

**Issue by Aureumsphere** [XHawk87/CreateYourOwnMenus#34]
Hey guys I feel lost.
I cant find the command which gives me the menu item to open the menu. So the command /grab is not working for me because I dont wanna have the items inside the menu but the item which executes the command /menu open [id].

Can someone help me out?

**Comment by XHawk87** [comment]
The solution is to have two menus, the first one is the main menu, and the second one (think of it like a kit) contains the item that opens the first menu. You use /menu grab on the second menu (kit)

**Comment by Andrei12333** [comment]
Use Essentials or EssentialsX kit system have only the menu item in your inventory then use "/kitcreate menu-{menuid} 0"
