### ISSUE TITLE
1.9 dev version not working

### ISSUE THREAD

**Issue by karmette** [XHawk87/CreateYourOwnMenus#38]
update: I'm using the version https://dev.bukkit.org/projects/createyourownmenus/files/809621
I typed /menu create shop Shop, or /menu script /give @p diamond, or /menu reload...

It replies with the same thing, /menu [create|open etc.] [parameters...]. there is no error message to tell me what I did wrong. is there a fix?
![image](https://user-images.githubusercontent.com/48113149/96042230-f447fc00-0e21-11eb-98dd-18319330010b.png)
no matter what I type, there's always no reply except that message.

**Comment by XHawk87** [comment]
Dunno, seems a bit sus... I'm voting Red :P

It should work afaik. You could try uninstall/reinstall the plugin, and full restart. If that doesn't work, go back another version and try that.
