### ISSUE TITLE
open menu with item

### ISSUE THREAD

**Issue by MCdutchwarrior** [XHawk87/CreateYourOwnMenus#5]
i want to let them open a menu with a item but when i do "/menu script add /menu open menu @p" it says that the player isn't online. (yes my menu is called menu)

**Comment by XHawk87** [comment]
Hi MCdutchwarrior.

The problem you are having is that the command is /menu open [player] [menu], not /menu open [menu] [player]. Just put the @p first and you should be fine! I.e.

/menu script add /menu open @p menu

Here is a full list of commands and how to use them: http://dev.bukkit.org/bukkit-plugins/createyourownmenus/pages/commands-and-permissions/

Have fun!

**Comment by MCdutchwarrior** [comment]
thank u so much my server is so much better with this plugin!! :)
