### ISSUE TITLE
How Do You Make a Menu Item Require a Permission

### ISSUE THREAD

**Issue by PokeNerd790** [XHawk87/CreateYourOwnMenus#7]
I'm Making a kitpvp server and i was wondering if you could make menu items require permissions to unlock certain kits please help

**Comment by XHawk87** [comment]
Hi PokeNerd790

You can require a permission for clicking a menu item by adding this to the top of the menu item script:

`/RequirePermission my.custom.permission.node`

"my.custom.permission.node" can be changed to whatever permission node that you want the player to need to use that menu item.

You can also use the specific menu permissions to allow players to open certain menus themselves.

`cyom.menu.myMenuID'

"myMenuID" should be changed to the ID of the menu you want them to be able to use.

**Comment by PokeNerd790** [comment]
thanks :)
