### ISSUE TITLE
my give command doesnt work 

### ISSUE THREAD

**Issue by PokeNerd790** [XHawk87/CreateYourOwnMenus#9]
i try to do this command but it doesnt work 
----------------------------------------------------------------------------------------------------------------------
/minecraft:give @p iron-sword 1 0 {Unbreakable:1,HideFlags:6,AttributeModifiers:[{Operation:0,UUIDLeast:1,UUIDMost:1,Amount:30.0,AttributeName:generic.attackSpeed,Name:attack},{Operation:0,UUIDLeast:2,UUIDMost:2,Amount:7.5,AttributeName:generic.attackDamage,Name:attack2}]}

**Comment by XHawk87** [comment]
Unfortunately, we have our own use for the curly braces `{}` (dynamic commands), from a time before data tags were added to Minecraft. We can't add support for data tags without breaking dynamic commands in older scripts. E.g. `/give {player to give diamond to} diamond 1`

However, you can get around this by putting the command in a custom scripting plugin like [Skript](https://dev.bukkit.org/projects/skript).

You first create a [custom command](http://njol.ch/projects/skript/doc/commands/).

In it, you [execute the command](http://njol.ch/projects/skript/doc/effects/#EffCommand) that gives them the sword.

It should look something like this:

`command /GiveSpecialSword <player>:
	executable by: console
	trigger:
		execute console command "/minecraft:give %player-argument% iron-sword 1 0 {Unbreakable:1,HideFlags:6,AttributeModifiers:[{Operation:0,UUIDLeast:1,UUIDMost:1,Amount:30.0,AttributeName:generic.attackSpeed,Name:attack},{Operation:0,UUIDLeast:2,UUIDMost:2,Amount:7.5,AttributeName:generic.attackDamage,Name:attack2}]}"
`

Finally, in the menu script, you run that custom Skript command instead: `/GiveSpecialSword @p`

If you need any help with Skript, there are a lot of nice people in their [forums](https://forums.skunity.com/) that can help you.

**Comment by PokeNerd790** [comment]
but i cant add skript so is there ANY other way ?

**Comment by XHawk87** [comment]
Skript is the best way. You can do a lot more with CYOM if you have Skript too.

However, there are other scripting plugins and command aliasing plugins out there that should be able to do the job.

If you can't use any other plugins, you might try performing some action that triggers a command block instead. Such as spawning a mob on a pressure plate or something.

**Comment by PokeNerd790** [comment]
what about a execute command would that work like /execute @p ~ ~ ~ <give command>

**Comment by PokeNerd790** [comment]
i found out i can do it using menu grab
